let animateCssClassName = [{
    label: '进入',
    children: [
      { label: '渐显', value: 'fadeIn', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '向右进入', value: 'fadeInLeft', bg_X: 120, bg_Y: -80, show_X: 120, show_Y: -560 },
      { label: '向左进入', value: 'fadeInRight', bg_X: 360, bg_Y: 0, show_X: 160, show_Y: -600 },
      { label: '向上进入', value: 'fadeInUp', bg_X: 360, bg_Y: 0, show_X: -120, show_Y: -480 },
      { label: '向下进入', value: 'fadeInDown', bg_X: 360, bg_Y: 0, show_X: -40, show_Y: -520 },
      { label: '向左长距进入', value: 'fadeInLeftBig', bg_X: 360, bg_Y: 0, show_X: -280, show_Y: -560 },
      { label: '向右长距进入', value: 'fadeInRightBig', bg_X: 360, bg_Y: 0, show_X: -240, show_Y: -600 },
      { label: '向上长距进入', value: 'fadeInUpBig', bg_X: 360, bg_Y: 0, show_X: -280, show_Y: -720 },
      { label: '向下长距进入', value: 'fadeInDownBig', bg_X: 360, bg_Y: 0, show_X: -160, show_Y: -765 },
      { label: '旋转进入', value: 'rotateIn', bg_X: 360, bg_Y: 0, show_X: -200, show_Y: -480 },
      { label: '左顺时针旋转', value: 'rotateInDownLeft', bg_X: 360, bg_Y: 0, show_X: 0, show_Y: -680 },
      { label: '右逆时针旋转', value: 'rotateInDownRight', bg_X: 360, bg_Y: 0, show_X: 0, show_Y: -680 },
      { label: '左逆时针旋转', value: 'rotateInUpLeft', bg_X: 360, bg_Y: 0, show_X: 0, show_Y: -680 },
      { label: '右逆时针旋转', value: 'rotateInUpRight', bg_X: 360, bg_Y: 0, show_X: 0, show_Y: -680 },
      { label: '弹入', value: 'bounceIn', bg_X: 360, bg_Y: 0, show_X: -280, show_Y: -520 },
      { label: '向右快速弹入', value: 'bounceInLeft', bg_X: 360, bg_Y: 0, show_X: 120, show_Y: -560 },
      { label: '向左快速弹入', value: 'bounceInRight', bg_X: 360, bg_Y: 0, show_X: 160, show_Y: -600 },
      { label: '向上弹入', value: 'bounceInUp', bg_X: 360, bg_Y: 0, show_X: -120, show_Y: -480 },
      { label: '向下弹入', value: 'bounceInDown', bg_X: 360, bg_Y: 0, show_X: -40, show_Y: -520 },
      { label: '斜切进入', value: 'lightSpeedIn', bg_X: 360, bg_Y: 0, show_X: 0, show_Y: -560 },
      { label: 'Y轴旋转', value: 'flip', bg_X: 360, bg_Y: 0, show_X: -80, show_Y: -720 },
      { label: '中心X轴旋转', value: 'flipInX', bg_X: 360, bg_Y: 0, show_X: -200, show_Y: -880 },
      { label: '中心Y轴旋转', value: 'flipInY', bg_X: 360, bg_Y: 0, show_X: -320, show_Y: -880 },
      { label: '左长半径旋转', value: 'rollIn', bg_X: 360, bg_Y: 0, show_X: -280, show_Y: -640 },
      { label: '由小变大进入', value: 'zoomIn', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '左变大进入', value: 'zoomInLeft', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '右变大进入', value: 'zoomInRight', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '向上变大进入', value: 'zoomInUp', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '向下变大进入', value: 'zoomInDown', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '向左滑动展开', value: 'slideInLeft', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '向右滑动展开', value: 'slideInRight', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '向上滑动展开', value: 'slideInUp', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '向下滑动展开', value: 'slideInDown', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
    ]
  },
  {
    label: '强调',
    children: [
      { label: '弹跳', value: 'bounce', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '闪烁', value: 'flash', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '放大缩小', value: 'pulse', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '放大缩小弹簧', value: 'rubberBand', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '左右晃动', value: 'shake', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '左右小幅晃动', value: 'headShake', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '左右扇形摇摆', value: 'swing', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '放大晃动缩小', value: 'tada', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '扇形摇摆', value: 'wobble', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: '左右上下晃动', value: 'jello', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
      { label: 'Y轴旋转', value: 'flip', bg_X: 360, bg_Y: 0, show_X: 360, show_Y: 200 },
    ]
  },
  {
    label: '退出',
    children: [
      { label: '渐隐', value: 'fadeOut', show_X: 360, show_Y: 200 },
      { label: '向左退出', value: 'fadeOutLeft', show_X: 360, show_Y: 200 },
      { label: '向右退出', value: 'fadeOutRight', show_X: 360, show_Y: 200 },
      { label: '向上退出', value: 'fadeOutUp', show_X: 360, show_Y: 200 },
      { label: '向下退出', value: 'fadeOutDown', show_X: 360, show_Y: 200 },
      { label: '向左长距退出', value: 'fadeOutLeftBig', show_X: 360, show_Y: 200 },
      { label: '向右长距退出', value: 'fadeOutRightBig', show_X: 360, show_Y: 200 },
      { label: '向上长距退出', value: 'fadeOutUpBig', show_X: 360, show_Y: 200 },
      { label: '向下长距退出', value: 'fadeOutDownBig', show_X: 360, show_Y: 200 },
      { label: '旋转退出', value: 'rotateOut', show_X: 360, show_Y: 200 },
      { label: '左顺时针旋转', value: 'rotateOutDownLeft', show_X: 360, show_Y: 200 },
      { label: '右逆时针旋转', value: 'rotateOutDownRight', show_X: 360, show_Y: 200 },
      { label: '左逆时针旋转', value: 'rotateOutUpLeft', show_X: 360, show_Y: 200 },
      { label: '右逆时针旋转', value: 'rotateOutUpRight', show_X: 360, show_Y: 200 },
      { label: '弹出', value: 'bounceOut', show_X: 360, show_Y: 200 },
      { label: '向左弹出', value: 'bounceOutLeft', show_X: 360, show_Y: 200 },
      { label: '向右弹出', value: 'bounceOutRight', show_X: 360, show_Y: 200 },
      { label: '向上弹出', value: 'bounceOutUp', show_X: 360, show_Y: 200 },
      { label: '向下弹出', value: 'bounceOutDown', show_X: 360, show_Y: 200 },
      { label: '光速进出', value: 'lightSpeedOut', show_X: 360, show_Y: 200 },
      { label: '中心X轴旋转', value: 'flipOutX', show_X: 360, show_Y: 200 },
      { label: '中心Y轴旋转', value: 'flipOutY', show_X: 360, show_Y: 200 },
      { label: '左长半径旋转', value: 'rollOut', show_X: 360, show_Y: 200 },
      { label: '由小变大退出', value: 'zoomOut', show_X: 360, show_Y: 200 },
      { label: '左变大退出', value: 'zoomOutLeft', show_X: 360, show_Y: 200 },
      { label: '右变大退出', value: 'zoomOutight', show_X: 360, show_Y: 200 },
      { label: '向上变大退出', value: 'zoomOutUp', show_X: 360, show_Y: 200 },
      { label: '向下变大退出', value: 'zoomOutDown', show_X: 360, show_Y: 200 },
      { label: '向左滑动收起', value: 'slideOutLeft', show_X: 360, show_Y: 200 },
      { label: '向右滑动收起', value: 'slideOutRight', show_X: 360, show_Y: 200 },
      { label: '向上滑动收起', value: 'slideOutUp', show_X: 360, show_Y: 200 },
      { label: '向下滑动收起', value: 'slideOutDown', show_X: 360, show_Y: 200 },
    ]
  }
]

export default animateCssClassName